/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_caration_tellstory_FFmpeg_FFmpegKit */

#ifndef _Included_l_com_myapplication_MainActivity
#define _Included_l_com_myapplication_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_caration_tellstory_FFmpeg_FFmpegKit
 * Method:    run
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_Java_sdd_time_com_myapplication_MainActivity_run
  (JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
